== Support annotations

Google provides a new annotations package.
This package  includes a number of metadata annotations, which you can use in your code, to prevent bugs. 

For example:

* @MainThread - the method code should be executed in the main thread
* @WorkerThread - the method code should not be executed in the main thread
* @Nullable - defines that a method return value or parameter can be null
* @NonNull - defines that a method return value or parameter cannot be null
* @Size - allows to specify the length of an array or list, e.g., @Size(2) or @Size(min=1) or @Size(multiple=2).
* @IntRange - allows to specify the range of possible integer values, e.g., @IntRange(from=0, to=255).
* @FloatRange - same as @IntRange but for floats.
* @CallSuper - specifies that classes that overrides such a method must call the override method in super


To use these annotations add the following dependency to your Gradle build file.

[source]
----
dependencies {
    compile 'com.android.support:support-annotations:22.2.0'
}
----

The following information describes the most important annotations. 
See http://tools.android.com/tech-docs/support-annotations for more information.

=== Nullness Annotations

The @Nullable annotation can be used to indicate that a given parameter or return value can be null. 
Similarly, the @NonNull annotation can be used to indicate that a given parameter (or return value) can not be null.

=== Threading Annotations: @UiThread, @WorkerThread, ...

If a method can only be called from a specific type of thread, you can annotate it with one of the following annotations:

* @UiThread
* @MainThread
* @WorkerThread
* @BinderThread

Example:

[source]
----
@WorkerThread
protected abstract Result doInBackground(Params... params);

@MainThread
  protected void onProgressUpdate(Progress... values) {
  }
----

	
The Android tooling uses these annotations to find potential errors in your code, via the Android Lint tool.
These checks are not perfect but can increase the code quality if considered during development.
	
