== Butterknife
	
http://jakewharton.github.io/butterknife/[Butterknife] is a light weight library to inject views into Android components.
It uses annotation processing.
	
The `@BindView` annotation allow to inject views and performs the cast to the correct type for you. 
The `@@OnClick(R.id.yourid)` annotation allows to add OnClickListener to a view. 
You can optional define the method parameter of the view in case you want it injected.
	
Butterknife includes also `findById` methods which simplify code that still has to find views on a View, Activity, or Dialog. 
It uses generics to infer the return type and automatically performs the cast.

[source,java]
----

import static butterknife.ButterKnife.findById;
....

View view = LayoutInflater.from(context).inflate(R.layout.thing, null);
TextView firstName = findById(view, R.id.first_name);
TextView lastName = findById(view, R.id.last_name);
ImageView photo = findById(view, R.id.photo);
----

You can also bind to fragments.
Butterknife also allows to unbind again, via the `Unbinder` object.

[source,java]
----
public class YourFragment extends Fragment {
  @BindView(R.id.button1) Button button1;
  @BindView(R.id.button2) Button button2;
  private Unbinder unbinder;

  @Override public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
    View view = inflater.inflate(R.layout.fancy_fragment, container, false);
    unbinder = ButterKnife.bind(this, view);
    // TODO Use fields...
    return view;
  }

  @Override public void onDestroyView() {
    super.onDestroyView();
    unbinder.unbind();
  }
}
----

Annotated attributes and methods cannot be private, as ButterKnife needs to be able to access them from a separate class.


