== How does Butterknife works

Butterknife uses annotation processing to generated modified Java classes based on your annotations.
Annotation processing is a tool build in javac for scanning and processing annotations at compile time.

You can define custom annotations and a custom processor to handle them.
These annotations are scanned and processed at compile time.
The annotation processor does not change the exiting input class but it generates a new Java class.
This generated Java code is compiled again as a regular Java class.

The Butterknife annotation processor scans all Java classes looking for the Butterknife annotations.
If a class contains these annotations, it generates a new class based on the _<original_class>__ViewBinding_ schema.

Here is the generate class from our example. 

[source,java]
-----
// Generated code from Butter Knife. Do not modify!
package com.vogella.android.butterknifeexample;

import android.support.annotation.CallSuper;
import android.support.annotation.UiThread;
import android.view.View;
import android.widget.TextView;
import butterknife.Unbinder;
import butterknife.internal.DebouncingOnClickListener;
import butterknife.internal.Utils;
import java.lang.IllegalStateException;
import java.lang.Override;

public class MainActivity_ViewBinding implements Unbinder {
  private MainActivity target;

  private View view2131165194;

  @UiThread
  public MainActivity_ViewBinding(MainActivity target) {
    this(target, target.getWindow().getDecorView());
  }

  @UiThread
  public MainActivity_ViewBinding(final MainActivity target, View source) {
    this.target = target;

    View view;
    target.title = Utils.findRequiredViewAsType(source, R.id.textView, "field 'title'", TextView.class);
    view = Utils.findRequiredView(source, R.id.button, "method 'submit'");
    view2131165194 = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.submit();
      }
    });
  }

  @Override
  @CallSuper
  public void unbind() {
    MainActivity target = this.target;
    if (target == null) throw new IllegalStateException("Bindings already cleared.");
    this.target = null;

    target.title = null;

    view2131165194.setOnClickListener(null);
    view2131165194 = null;
  }
}
----

Once you call `ButterKnife.bind(this)`, this will call into the generated constructor and perform the view injections and listener registration.



