[[Parcelable]]

= Understanding Parcelable in Android

== Using Bundle to pass data between Android components 

The `Bundle` object which is used to pass data to Android components is a key/value store for specialized objects.
It is similar to a Map but can only contain these specialized objects

You can place the following objects types into a `Bundle`:

* String
* primitives
* Serializable
* Parcelable

If you need to pass your customer objects via a `Bundle`, you should implement the `Parcelable` interface.

== Implementing Parcelable

A _Parcelable_ is the Android implementation of the Java Serializable. 
It assumes a certain structure and way of processing it.
This fast it relatively fast  compared 	to the standard Java serialization.
	
	
To allow your custom object to be parsed to another component they need to implement the `android.os.Parcelable` interface.
It must also provide a static final method called `CREATOR`	which must implement the `Parcelable.Creator` interface.
	
	
[source,java]
----
include::res/parcel/Student.java[]
----
	
Once you have defined this, you can put it into the extra of an intent.
	
[source,java]
----
include::res/parcel/intent.java[]
----
	

To access the parcel on the other side, you can use the following example code.
	
[source,java]
----
include::res/parcel/getParcel.java[]
----
	



