== Resources

=== Resource files

(((Resource files)))
(((Resource qualifiers)))
Static resources like images and XML configuration files are used in Android applications. 
		
		
Resource files must be placed in the _/res_ directory of your application in a predefined sub-folder. 
The specific sub-folder depends on type of resource which is stored.
You can also append additional qualifiers to the folder name.
These are called _resource qualifiers_.
These qualifiers indicate that the related resources should be used for special device  configurations. 
For example, you can specify that a layout file is only valid for a certain screen size.

		
The following table gives  an overview of the supported resources and their standard folder prefixes.

.Resources
[cols="1,1,4",options="header"]
|===
|Resource |Folder |Description

|Drawables
|_/res/drawables_
|Images (e.g., png or jpeg files)or vector drawables or XML files   which scale automatically with the density of the Android device

|Simple Values
|_/res/values_
|Used to define strings, colors, dimensions, styles and
		static
		arrays of strings or integers via XML files. By
		convention each
		type is
		stored
		in a separate file, e.g., strings are defined in
		the
		_res/values/strings.xml_
		file.
		
|Layouts
|_/res/layout_
|XML files with layout descriptions are used to define the user interface for activities and fragments.

|Styles and themes
|_/res/values_
|Files which define the appearance of your Android application.

|Animations
|_/res/animator_
|Defines animations in XML for the animation API which allows to animate arbitrary properties of objects over time.

|Raw data
|_/res/raw_
|Arbitrary files saved in their raw form. You access them via an `InputStream` object.

|Menus
|_/res/menu_
|Defines the actions which can be used in the toolbar of the application.

|===
		
=== Example: Defining strings, string arrays, colors and dimensions
		
For example, the following _values.xml_ file in the _/res/values_ folder  defines a few String constants, a String array, a color and a
dimension.
		
[source,xml]
----
include::res/resources/values.xml[]
----

=== Resource files and R.java

		
Every relevant resource in the _res_ folder, gets an ID assigned by the Android build system.
The Android tooling generates a _R.java_ file which contains the generated
values.
These references are static integer values.
		
If you add a new resource file, the corresponding reference is automatically created in a _R.java_ file.
Manual changes in the
_R.java_
file are not
necessary and will be overwritten
by the
tooling.
The Android
system
provides
methods to access the
corresponding
resource files
via these IDs.
		
		
For
example, to
access a
String with the
`R.string.yourString`
ID in your source code,
you would use the
`getString(R.string.yourString)`
method defined on the
`Context`
class.
		
=== Layout files
		
Android activities define their user interface with
views
(widgets) and
fragments.
This user interface
can be
defined via
XML
layout
resource
files in the
<filename class="filename">/res/layout_
folder or via Java code. You
can
also
mix
both approaches.
		
		
Defining layouts via
XML layout files
is the
preferred way.
This
separates the programming logic
from the layout
definition. It
also
allows the definition of different layouts
for different
devices.
		

		
A layout resource file is referred to as
_layout_. A layout
specifies the
`ViewGroups`,
`Views`,
their
relationship and
their attributes via an XML representation.
		
The following code is an example for a simple layout file.
		
[source,xml]
----
include::res/layout/activity_main.xml[]
----
		
A layout is assigned to an activity via the `setContentView()` method calls, as demonstrated in the following example code.

[source,java]
---- 
include::res/layout/MainActivity.java[]
----

=== Performance considerations with layouts
Calculating the layout and drawing the views is a resource intensive operation. 
You should use the simplest layout possible to achieve good performance.
For example, you should avoid nesting layout
managers
too deeply or avoid using
complex layout managers in case a
simple layout manager is sufficient.
		
	
=== Good practices for resources IDs
(((Resource ID,Good practices)))
If a view needs to be accessed via Java or XML code, you have to give the view a unique ID via the `android:id` attribute. 
To assign a new
ID to a view
use the
`android:id`
attribute of the corresponding element in the layout file.

		

		
The Android SDK uses the
_camelCase_
notation
for most of its IDs, e.g.,
`buttonRefresh`. It is good practice to follow this approach.
		
		
The
following shows an example in which a button
gets the
`button1`
ID assigned via the
`android:id="@+id/button1"`
parameter.
By conversion this statement
creates a new ID if necessary in the
`R.java`
file and assigns the defined ID
to the corresponding
view.
		

[source,xml]
----
include::res/snippets/id.txt[]
----

		
It is good practice to
define IDs in one central configuration file. This is typically called
_ids.xml_
and placed
in the
_/res/values_
folder. This allows you to use the predefined ID in your layout file. If you want to define the id in a separate
file, you first
need to remove the @+id entries in your layout
files, otherwise you
get an error messages that these
files have already been created. The following listing shows
an example for such
a file.
		
		
[source,xml]
----
include::res/ids/ids.xml[]
----
		
[source,xml]
----
include::res/ids/activity_main.xml[]
----
		
[NOTE]
====
While the above is good practice for real projects, the tutorials of this {textselfreference} avoid the usage of a separate id file as this setup is time consuming.
====

=== System resources
		
Android also provides resources. 
These are called _system resources_. 
System resources are distinguished from local resources by the `android` namespace prefix. 
For example, `android.R.string.cancel` defines the platform string for a cancel operation.

=== References to resources in code
		
The `Resources` class allows to access individual resources. 
An instance of the `Resources` class can be retrieved via the `getResources()` method of the `Context` class. 
As activities and services extend the `Context` class, you can directly use this method in implementations of these components.


An instance of the `Resources` class is also required by other Android framework classes. 
For example, the following code shows how to create a `Bitmap` file from a reference ID.

[source,java]
----
include::res/resources/LoadBitmap.java[]
----
		
=== Accessing views from the layout in an activity
		
In your activity (and fragment) code you frequently need to access the views to access and modify their properties.

		
In an activity you can use the `findViewById(id)` method call to search for a view in the current layout. 
The `id` is the ID attribute of the view in the layout. 
The usage of this method is demonstrated by the following code.
		
		
[source,java]
----
@Override
protected void onCreate(Bundle savedInstanceState) {
	super.onCreate(savedInstanceState);
	setContentView(R.layout.activity_main);
	TextView textView = (TextView) findViewById(R.id.mytext);
        
    // TODO do something with the TextView
}
----
		
It is also possible to search in a view hierarchy with the `findViewById(id)` method, as demonstrated in the following code snippet.

[source,java]
----
// search in the layout of the activity
LinearLayout linearLayout = (LinearLayout) findViewById(R.id.mylayout);

// afterwards search in linearLayout for another view
TextView textView = (TextView) linearLayout.findViewById(R.id.mytext);

// note, you could have directly searched for R.id.mytext, the above coding
// is just for demonstration purposes
----


[TIP]
====
You could also build a utility method which makes access to views easier.

[source,java]
----
package com.example.android.test;

import android.app.Activity;
import android.view.View;

public class UiUtils {
   public static <T extends View> T findView(View root, int id)      {
      return (T) root.findViewById(id); }

   public static <T extends View> T findView(Activity activity, int id)      {
      return (T) activity.getWindow().getDecorView().getRootView().findViewById(id); }
}
----

This would allow you to find the view without explicit cast in your view hierarchy.

[source,java]
----
Button button = UiUtils.findView(this, R.id.button);
----
====
		
=== Reference to resources in XML files
		
In your XML files, for example, your layout files, you can refer to other resources via the `@` sign.
		
		
For example, if you want to refer to a color, which is defined in an XML resource, you can refer to it via `@color/your_id`.
Or if you defined a `String` with the `"titlepage"` key in an XML resource, you could access it via `@string/titlepage`
		
To use an Android system resource, include the `android` namespace into the references, e.g., `android.R.string.cancel`.
		
=== Using assets?
		
The _res_ directory contains structured values which predefined semantics for the Android platform.
The _assets_ directory can be used to store any kind of data.
You can access files stored in this folder based on their path. 
The _assets_ directory also allows you to have sub-folders.

[NOTE]
====
You could also store unstructured data in the _/res/raw_ folder. 
But it is considered good practice to use the _assets_ directory for such data.
====	
		
You access this data via the `AssetsManager` which you can access via the `getAssets()` method from an instance of the `Context` class.
		
The `AssetsManager` class allows you to read a file in the _assets_ folder as `InputStream` with the `open()` method. 
The following code shows an example for this.
		
[source,java]
----
include::res/assets/assets.java[]
----
		

