== Overview of network access on Android

=== Accessing the network in Android

Within an Android application you should avoid performing long running operations on the user interface thread. 
This includes file and network access.

The Android system crashes your application with a `NetworkOnMainThreadException` exception, if you access  network is accessed from the main thread.

Android contains the standard Java network `java.net` package which can be used to access network resources. 
The base class for HTTP network access in the `java.net` package is the `HttpURLConnection` class.


Performing network operations with standard Java API can be cumbersome. 
You have to open and close a connections, enable caches and ensure to perform the network operation in a background thread.

To simplify these operations several popular Open Source libraries are available. 
The most popular ones are the following:

* OkHttp for efficient HTTP access
* Retrofit for REST based clients
* Glide for image processing

[NOTE]
====
Prefer using OkHttp over the usage of `HttpURLConnection`.
It is faster than the standard Java library and has a better API.
====

=== Permission to access the network

To access the Internet your application requires the `android.permission.INTERNET` permission.
On modern Android API versions, this permission is automatically granted to your application.


=== Check the network availability
	
The network on an Android device is not always available. 
To check the network state your application requires the `android.permission.ACCESS_NETWORK_STATE` permission.
You can check the network is currently available via the following code.

[source,txt]
----
include::res/status/check.txt[]
----	
	
This requires the `ACCESS_NETWORK_STATE` permission.





