== Defining fragments for your activity

=== Adding fragments statically to the layout file
		
To use your new fragment, you can statically add it to an XML layout. 
In this case the `android:name` attribute points to the corresponding class as demonstrated by the following code snippet.
		
[source,xml]
----
include::res/fragments/activity_rssfeed.xml[]
----
		
Using this scenario makes sense in case you have different static layout files for different device configurations.
		
=== Handling dynamics in fragments
(((FragmentManager)))
The `FragmentManager` class allows you to add, remove and replace fragments in the layout of your activity.
It can accessed in an activity via the `getFragmentManager()` method. 	
		
The modifications must be performed in a transaction via the `FragmentTransaction` class.
		
To modify the fragments in an activity you typically define a `FrameLayout` placeholder in the layout file.
		
[source,xml]
----
include::res/fragmentsdynamic/activity_rssfeed.xml[]
----
		
		
You use the `FragmentManager` to replace the container with a fragment.
		
[source,java]
----
include::res/fragmentsdynamic/replace.java[]
----
		
		
A new fragment replaces an existing fragment in this container.
		
If you want to add the transaction to the backstack of Android, you use the `addToBackStack()` method.
This adds the action to the history stack of the _activity_ and allows the user to revert this change via the back button.
		
=== Check if a fragment is present in the layout
		
To check if a fragment is part of your layout you can use the `FragmentManager` class. 
The `isInLayout()` method works on if the fragment as added to the activity via its layout.
		
[source,java]
----
include::res/fragments/check.java[]
----
		
=== Determine how many fragments are present
(((Multi pane mode, Determine which mode you are in)))
(((Dual pane mode, Determine which mode you are in)))
(((Single pane mode, Determine which mode you are in)))
As the logic in the activity depends on the scenario (single/multi pane), you typically write a check to determine in which mode you are.
There are several approaches to perform this. 
One way is to define a configuration file in the _values_ resource folder.
The key / value pair defaults to false and a additional configuration file set this value to true for the desired screensize.
		
For example this is a possible default _config.xml_ configuration file.

[source,xml]
----
<resources>
    <item type="bool" name="twoPaneMode">false</item>
</resources>
----
    
Create the same file in your _res/values-land_ folder with a different value.

In the _values-land_ folder you would place a _config.xml_ configuration file with a different value.
		
[source,xml]
----
<resources>
    <item type="bool" name="twoPaneMode">true</item>
</resources>
----

In your code you can access the state via the following snippet.
		
[source,java]
----
include::res/mode/Access.java[]
----

=== Adding fragments transition to the backstack
	
You can add a `FragmentTransition` to the backstack to allow the user to use the back button to reverse the transition.
	
For this you can use the `addToBackStack()` method on the `FragmentTransition` object.

=== Animations for fragment transitions
	
During a fragment transaction, you can define animations based on the _Property Animation_ API via the `setCustomAnimations()` method.
	
You can also use several standard Android animations via the `setTransition()` method call.
These are defined via the constants starting with `FragmentTransaction.TRANSIT_FRAGMENT_*`.
	
Both methods allow you to define an entry animation and an existing animation.


=== Persisting data in fragments

==== Persisting data between application restarts
		
Frequently in your Android application you need to persist your application data. For this, you can for example
use an
SQLite database or a file.
		

==== Persisting data between configurations changes
		
If you want to persist data between configuration changes, you can also use the application object.
		
		
In addition to that you can use the `setRetainState(true)` method call on the fragment. 
This retains the fragment instances between configuration changes.
It only works if the fragments are not added to the backstack. 
In this case the data must be stored as member (field).

[NOTE]
====
Using this method is not recommended by Google for fragments which have a user interface. 
See <<headlessfragments1>>.
====

You can use the `onSaveInstanceState()` method to place the data in the `Bundle`.
You can retrieve that data the `onActivityCreated()` method.
		

