== Using data binding in Android applications

=== Introduction to data binding in Android

Android offers support to write declarative layouts using data binding.
This minimizes the necessary code in your application logic to connect to the user interface elements.

The usage of data binding requires changes in your layout files.
Such layout files starts with a `layout` root tag followed by a `data` element and a `view` root element. 
The data elements describe data which is available for binding.
This `view` element contains your root hierarchy similar to layout files which are not used with data binding.
References to the data elements or expressions within the layout are written in the attribute properties using the `@{}` or `@={}`,

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android">
   <data>
       <variable name="temp" type="com.vogella.android.databinding.TemperatureData"/> #<1>
   </data>
   <LinearLayout #<2>
       android:orientation="vertical"
       android:layout_width="match_parent"
       android:layout_height="match_parent">
       <TextView 
       	android:layout_width="wrap_content"
       	android:layout_height="wrap_content"
       	android:text="@{temp.location}"/>
       <TextView 
       	android:layout_width="wrap_content"
         android:layout_height="wrap_content"
         android:text="@{temp.celsius}"/>
   </LinearLayout>
</layout>
----

<1> The user variable within data describes a property that may be used within this layout.
<2> Normal view hierarchy

Android data binding generates a `Binding` class based on this layout.
This class holds all the bindings from the layout properties, i.e., the defined variable to the corresponding views. 
It also provides generated setters for your data elements from the layout.
The name of the generated class is based on the name of the layout file.
This name is converted to Pascal case and the `Binding` suffix is added to it. 
For example, if the layout file is called `activity_main.xml`, the generate class is called `ActivityMainBinding`.
You can inflate the layout and connect your model via this class or the `DataBindingUtil` class.


[source,xml]
----

TemperatureData temperatureData = // your data is created here
ActivityMainBinding binding = DataBindingUtil.setContentView(this, R.layout.activity_main);
binding.setTemp(temperatureData); // generated setter based on the data in the layout file
----

You can also inflate the layout, which is useful for late binding, as for example, in a `RecyclerView`.

[source,java]
----
ActivityMainBinding binding = ActivityMainBinding.inflate(getLayoutInflater(), container, attachToContainer);
// get the root view
View view = binding.getRoot();
// do more stuff
TemperatureData temperatureData = // your data is created here
binding.setTemp(temperatureData); // generated setter based on the data in the layout file
----


You can also inflate layouts for `RecyclerView`, `ViewPager`, or other things that aren’t setting the Activity contents.

=== Enable data binding in your Android application
		
To enable the usage of data binding in your Android application, add the following snippet to the app/build.gradle file.
			
[source,gradle]
----
android {
    ....
    dataBinding {
        enabled = true
    }
}
----


=== Data binding for events
		
Events may be bound to handler methods directly, similar to the way `android:onClick` can be assigned to a method in the activity. 
Event attribute names are governed by the name of the listener method with a few exceptions. 
For example, `View.OnLongClickListener` has a `method onLongClick()`, so the attribute for this event is `android:onLongClick`.
		
To assign an event to its handler, use a normal binding expression, with the value being the method name to call. 
The binding expression can assign the click listener for a View.

=== Updating the user interfaces with changes from the data model

Any plain old Java object (POJO) can be used for data binding.
But to update the UI if the data object change, these objects must be able to notify about data changes. 
There are three different data change notification mechanisms:
* Observable objects
* observable fields
* observable collections

Android provides the `BaseObservable` class which you can extend.
The data class is responsible for notifying when the properties change. 
This is done by assigning a `@Bindable` annotation to the getter and notifying in the setter.

[source,java]
----
package com.vogella.android.databinding;


import android.databinding.BaseObservable;
import android.databinding.Bindable;

import java.util.Observable;

public class TemperatureData extends BaseObservable {
    private String celsius;

    public TemperatureData(String celsius) {
        this.celsius = celsius;
    }

    @Bindable	 	                     <1> 
    public String getCelsius() {
        return celsius;
    }

    public void setCelsius(String celsius) {
        this.celsius = celsius;
        notifyPropertyChanged(BR.celsius);         <2> 
    }
}
----

<1> Define a relevant getter
<2> Notify any listeners, BR.celsius is a generated class


This listener is invoked on every update and it updates the corresponding views. 
This ensures that updates in the model updates also the UI.
				
=== Example for using data binding
	
A sample file looks like the following listing.

	
The user variable within data describes a property that may be used within this layout.

The data object used with this layout may look like the following listing.

	
[source,java]
----
include::res/User.java[]
----
	
[source,java]
----
include::res/usage.java[]
----	


