== Exercise: Using data binding in Android applications
		
In this exercise you learn how to interact between your user interface widgets using data binding.
Create a new Android application for this exercise, with the `com.vogella.android.databinding` top level package.
		
=== Activate the usage of data binding
		
Open your _app/build.gradle_ file and activate the usage of data binding. 

[source,gradle]
----
include::res/exercise_layoutbutton/build.gradle[]
----
		
[WARNING]
====
Ensure you pick the correct build file.
====

=== Create classes for the view interaction

Create the following classes.

[source,java]
----
include::res/exercise_layoutbutton/TemperatureData.java[]
----

[NOTE]
====
After the definition of the layout file, the missing BR class is generated.
====

[source,java]
----
include::res/exercise_layoutbutton/MainActivityContract.java[]
----

[source,java]
----
include::res/exercise_layoutbutton/MainActivityPresenter.java[]
----

=== Adjust layout file and activity to use data binding
		
Change the layout to the following.
		
[source,xml]
----
include::res/exercise_layoutbutton/activity_main.xml[]
----
		
[NOTE]
====
You see some warning messages in the editor, e.g., because you used hard-codes strings.
For this exercise we ignore these warnings.
====

[source,java]
----
include::res/exercise_layoutbutton/solution_MainActivity.java[]
----	
Adjust your `MainActivity` code to activate data binding.

=== Convince Android Studio to compile your application

If the BR class is missing, select menu:Build[Clean] followed by menu:Build[Make Project].

=== Validate your application

Start your application. 
If you press the button, a small popup should be shown with the correct data.

The first text view should 
The second `TextView` should update automatically, if you type in the `EditText` field.



