== Displaying dialogs with DialogFragments

=== Using fragments for dialogs

A `DialogFragment` is a fragment that displays a modal window, floating on top of the current activity window. 		
An instance of `DialogFragment` can be used to display an existing `Dialog`  implementation dialog or a custom view hierarchy.

The `Dialog` class is the base class for implementing a dialog. 
Android provides several standard dialog implementation, `AlertDialog`, `ProgressDialog`, `DatePickerDialog` or `TimePickerDialog`.
Your `DialogFragment` can implement the `onCreateDialog` method and return such a dialog implementation.

If you want to create your custom view hierarchy you can build this in the `onCreateView()` method of the fragment.
		
=== Communication to the activity via the DialogFragment
		
Your implementation of `DialogFragment` communicates similar to other fragment to the activity. 
A good practice is that the fragment defines an interface which the activity must implement.
The fragment can call back into the activity without knowing the implementation details of the activity.

		