== Exercise: Using the DialogFragment class
		
The following demonstrates the usage of the `DialogFragment` fragment to display modal windows..
Both the re-use of an dialog implementation and a custom layout for the dialog fragment is shown.

=== Create project and layout files

Create a new Android project with the `com.android.vogella.com.dialogfragmentexample` package.
		
Add at least two buttons to the activity layout.
Both should point to the `onClick` method via their `android:onClick` property.
		
Create the following layout file, called `fragment_username.xml`.
		
[source,xml]
----
include::res/dialog/fragment_username.xml[]
----
		
=== Create fragments and adjust activity

Create the following two fragment classes.

[source,java]
----
include::res/dialog/MyAlertDialogFragment.java[]
----
		
[source,java]
----
include::res/dialog/MyDialogFragment.java[]
----
		
Change the code of your activity to the following listing.
		
[source,java]
----
include::res/dialog/MainActivity.java[]
----
	
=== Test dialog usage

If you run your application and click the corresponding button, your dialog should get displayed.
		
