== Gradle for building Android applications
	
=== Build files for Android applications

The build process of Android projects is handled by the Gradle build system. 
If you create a new project in Android studio, the Gradle build scripts are automatically created. 
Android studio wraps the Gradle runtime, hence no additional installation is required.

The Gradle build system is designed to support complex scenarios in creating Android applications:

* Multi-distribution: the same application must be customized for several clients or companies
* Multi-apk: supporting the creation of multiple apk for different device types while reusing parts of the code
	
You can also use a wrapper script created by Gradle. 
This wrapper  allows you to run a Gradle build without any additional installation from the command line.

If you press the run button in Android Studio, it triggers the corresponding Gradle task and starts the application.


[NOTE]
====
You find the available versions of the Android Gradle plug-in under the following URL: https://jcenter.bintray.com/com/android/tools/build/gradle/
====


=== Conversion process from source code to Android application

The Java source files are converted to Java class files by the Java compiler.
The Android SDK contains a tool called _dx_ which converts Java class files into a _.dex_ (Dalvik Executable) file. 
All class files of the application are placed in this _.dex_ file. 
During this conversion process redundant information in the class files are optimized in the _.dex_ file.
For example, if the same `String` is found in different class files, the _.dex_ file contains only one reference of this `String`.
	
These _.dex_ files are therefore much smaller in size than the corresponding class files.

The _.dex_ file and other resources, e.g., the images and XML files, are packed into an _.apk_ (Android Package) file. 
The program _aapt_ (Android Asset Packaging Tool) performs this step.
		
The resulting _.apk_ file contains all necessary data to run the Android application and can be deployed to an Android device via the _adb_ tool.

As of Android 5.0 the _Android RunTime_ (ART) is used as runtime for all Android applications.
ART uses a combination of _Ahead Of Time_ and _Just In Time _ compilation. 
During the installation of  an application on an Android device, the application code is translated into machine code.
		
The `dex2oat` tool takes the .dex file created by the Android tool chain and compiles that into an Executable and Linkable Format (ELF file).
This file contains the dex code, compiled native code and meta-data.
Keeping the .dex code allows that existing tools still work.
		

=== Using Gradle on the command line
	
You can start your Gradle build also from the command line.
For this execute the following command from the main project directory. 
This requires that Gradle is installed on the machine or that you use the Gradle wrapper (gradlew) to execute the build.
The wrapper downloads Gradle if necessary.
Here is an overview of the important Android Gradle tasks:

.Android Gradle build targets
|===
|Command |Description


|`./gradlew build`
|build project, runs both the assemble and check task

|`./gradlew clean build`
|build project complete from scratch

|`./gradlew clean build`
|build project complete from scratch

|`./gradlew test`
|Run the tests

|`./gradlew connectedAndroidTest`
|Run the instrumentation tests

|===

To see all available tasks, use the `gradlew wrapper` command.

[source,console]
----
include::res/gradle/runBuild.sh[]
----

This command creates in the _build_ folder the output of the Gradle build. 
By default, the Gradle build creates two _.apk_ files in the _build/outputs/apk_ folder.
	
To build and start your unit tests on the JVM use the following command.

[source,console]
----
include::res/gradle/runTests.sh[]
----
	
To build and start your instrumented tests on your Android device use the following command.

[source,console]
----
include::res/gradle/runInstrumentedTests.txt[]
----

[[building_gradle_minify]]
=== Removing unused resources and Java classes via resource shrinking
	
The Gradle build system for Android supports resource shrinking at build time. 
This automatically removes resources that are unused from the packaged application.
In addition to that, this also removes unnecessary resources from libraries you are depending on.
This can hugely reduce the size of your application.

To enable resource shrinking, update your build file similar to the following snippet.

[source,java]
----
include::res/minify/build.gradle[]
----

=== Defining dependencies and keepting the version external

A good practice is to define the version of your library dependencies outside the dependencies closure for better maintenance.


[source]
----

ext {
    // App dependencies
    junitVersion = '4.12'
    mockitoVersion = '1.10.19'
    powerMockito = '1.6.2'
    hamcrestVersion = '1.3'
}

dependencies {
    // Dependencies for local unit tests
    testCompile "junit:junit:$junitVersion"
    testCompile "org.mockito:mockito-all:$mockitoVersion"
    testCompile "org.hamcrest:hamcrest-all:$hamcrestVersion"
    testCompile "org.powermock:powermock-module-junit4:$powerMockito"
    testCompile "org.powermock:powermock-api-mockito:$ext.powerMockito"
}

----

TIP: If you put the ext closure into the root build file, you can access its properties for example with '$rootProject.ext.junitVersion'.

