== Exercise: Use JobScheduler from a receiver


You learn how to use the Android job scheduler to trigger a service from a broadcast receiver.
You also register this receiver for the _boot completely_ broadcast.
The registered receiver uses the job scheduler to trigger your custom service on a regular basis.

=== Create the receiver

Create the following utility class.

[source,java]
----
include::res/receiver/Util.java[]
----

Create the following receiver

[source,java]
----
include::res/receiver/MyStartServiceReceiver.java[]
----

Register the receiver in the Android manifest for the BOOT_COMPLETED event.
[source,xml]
----
<receiver android:name="MyStartServiceReceiver" >
	<intent-filter>
		<action android:name="android.intent.action.BOOT_COMPLETED" />
	</intent-filter>
</receiver>
----

=== Create your job 

[source,java]
----
include::res/receiver/ScheduleWordUpdateJobService.java[]
----
=== Trigger the boot completed event from the command line

[source,shell]
----
~/Android/Sdk/platform-tools$ ./adb root
~/Android/Sdk/platform-tools$ ./adb shell am broadcast -a android.intent.action.BOOT_COMPLETED
----
=== Validate 

Trigger the boot completed event from the command line or reboot your device.
Start your application.
Update the data in the list, the list should grow longer until it reaches 20 entries.

