== Exercise: Add a toolbar to your application

=== Add a refresh icon
		
Continue to use the _RSS Reader_ project. 
Create a new drawable called _ic_refresh_ via the menu:File[New>Vector Asset] menu entry.
Select a fitting image from the provided example images.

=== Add menu resources
		
Create a new XML resource for your menu called _mainmenu.xml_. 
Add on entry to the file so that the resulting XML file, similar to the following listing. 
		
[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<menu xmlns:android="http://schemas.android.com/apk/res/android" >
	<item android:title="Refresh"
        android:icon="@drawable/ic_refresh"
        android:id="@+id/action_refresh"
        android:showAsAction="ifRoom" />
    <item
        android:id="@+id/action_settings"
        android:title="Settings"
        android:showAsAction="never"
        >
    </item>
     <item
        android:id="@+id/action_network"
        android:title="Network Setting"
        android:showAsAction="never"
        >
    </item>
</menu>
----

	
=== Turn of the default action bar from the styling

Turn of the default one via the _res/values/styles.xml_ file.

[WARNING]
====
This styling requires that `RssFeedActivity` extends `Activity`. 
Please double-check this.
====

[source,xml]
----
<resources>
    <!-- Base application theme. -->
    <style name="AppTheme" parent="android:Theme.Material.Light.NoActionBar">
        <!-- Customize your theme here. -->
    </style>
</resources>	
----

=== Add a toolbar view to your activity layout
		
Change the layout files of your `RssfeedActivity` activity to also contain a toolbar entry.
		
[source,xml]
----
include::res/rssfeed/activity_main.xml[]
----

Do the same for the layout for the portrait mode.

[source,xml]
----
include::res/rssfeed/activity_main_port.xml[]
----
		
		
Change your `RssfeedActivity` class to the following code, to configure the toolbar view.
		
[source,java]
----
include::res/social/OverviewActivity.java[]
----

=== Run the application and test the toolbar
		
Run your application and validate that you can select both of your actions. 
Ensure that a Toast is displayed if you select the different entries.
		

[NOTE]
====
If your device or emulator has an _Option_ menu button, you will not see the overflow menu. 
You need to press the _Option_ key to see the actions which are part of the overflow menu.
====	
